model :
    n_pois : 50
    zdim : 256
    activation : tanh
    device : cuda:0
    photo_coeff : 1.0
    percep_coeff : 0.2
    reg_detail_coeff : 1.0
    uv_gan_coeff : 0.001
    img_gan_coeff : 0.001
    grad_coeff : 1.0
    symmetry_coeff : 0.1
    chroma_coeff : 0.1
    style_coeff : 1.0
    reg_light_coeff : 1.0
    learning_rate : 1e-4
train :
    data_name : celeba
    n_epochs : 10
    batch_size : 16
    val_interval : 10
    visualize_samples : 10
    